random_seed: 42
random_forest:
  n_estimators: 100
  criterion: entropy
  max_depth: 7
  min_samples_split: 2
  min_samples_leaf: 1
  bootstrap: true
  oob_score: false
  n_jobs: -1
  max_features: 10
categorical_features:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - native_country