random_seed: 42
data: clean_census.csv
train_params:
  n_estimators: 100
  criterion: entropy
  max_depth: 7
  max_features: 10
categorical_features:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - native_country
model_output: random_forest.pkl
encoder_output: onehot_encoder.pkl
label_binarizer_output: label_binarizer.pkl